name: publish
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - run: bin/build
      - run: |
          tar \
            --dereference --hard-dereference \
            --directory "output" \
            -cf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
          if-no-files-found: error
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
        with:
          artifact_name: site
